import { Lecture, VisualAsset, WorshipSong } from '@/types/workflow';

export function exportToMarkdown(
  lecture: Lecture,
  visualAssets: VisualAsset[] = [],
  worshipSongs: WorshipSong[] = []
): string {
  let markdown = `# ${lecture.title}\n\n`;
  markdown += `**Scripture Reference:** ${lecture.scriptureReference}\n\n`;
  markdown += `*Generated by BSF Lecture Assistant*\n\n`;
  markdown += `---\n\n`;

  // Worship Songs Section
  if (worshipSongs.length > 0) {
    markdown += `## Worship Songs\n\n`;
    worshipSongs.forEach(song => {
      markdown += `### ${song.title}\n`;
      markdown += `- **Artist/Source:** ${song.artist} - ${song.source}\n`;
      markdown += `- **Category:** ${song.category}\n`;
      markdown += `- **Placement:** ${song.placement}\n`;
      markdown += `- **Thematic Connection:** ${song.thematicConnection}\n\n`;
    });
    markdown += `---\n\n`;
  }

  // Introduction
  markdown += `## Introduction\n\n`;
  markdown += `${lecture.introduction.storyOpening}\n\n`;
  markdown += `*(Story continues...)*\n\n`;

  // Body - handle both array and object structures
  const bodyAny = lecture.body as any;
  const bodyArray = Array.isArray(bodyAny) 
    ? bodyAny 
    : (bodyAny?.divisions || Object.values(bodyAny || {}).filter((d: any) => d && d.title));
  
  bodyArray.forEach((division: any, index: number) => {
    markdown += `## Division ${index + 1}: ${division.title || 'Untitled'}\n\n`;
    markdown += `**Scripture:** ${division.scriptureRange || division.scripture_reference || 'N/A'}\n\n`;
    markdown += `### Exposition\n${division.exposition || ''}\n\n`;
    markdown += `### Principle\n${division.principle || ''}\n\n`;
    markdown += `### Applications\n\n`;
    
    // Handle different application structures
    const apps = division.applications || {};
    const youngPro = apps.youngProfessionals || apps.young_men_20s_30s || apps.young_adults_20s_30s || {};
    const midLife = apps.fathersMidLife || apps.middle_aged_men_40s_50s || apps.middle_aged_40s_50s || {};
    const elders = apps.elders || apps.older_men_60s_plus || {};
    
    markdown += `**Young Professionals (20s-30s):** ${youngPro.question || 'N/A'}\n\n`;
    if (youngPro.discussionPoints?.length) {
      markdown += `   - ${youngPro.discussionPoints.join('\n   - ')}\n\n`;
    }
    
    markdown += `**Fathers/Mid-life (40s-50s):** ${midLife.question || 'N/A'}\n\n`;
    if (midLife.discussionPoints?.length) {
      markdown += `   - ${midLife.discussionPoints.join('\n   - ')}\n\n`;
    }
    
    markdown += `**Elders (60s+):** ${elders.question || 'N/A'}\n\n`;
    if (elders.discussionPoints?.length) {
      markdown += `   - ${elders.discussionPoints.join('\n   - ')}\n\n`;
    }
    
    markdown += `---\n\n`;
  });

  // Conclusion
  markdown += `## Conclusion\n\n`;
  markdown += `${lecture.conclusion.storyResolution}\n\n`;
  markdown += `### Call to Action\n${lecture.conclusion.callToAction}\n\n`;
  markdown += `### Closing Prayer\n${lecture.conclusion.closingPrayer}\n\n`;
  markdown += `---\n\n`;

  // Visual Assets
  if (visualAssets.length > 0) {
    markdown += `## Visual Assets (AI Image Prompts)\n\n`;
    markdown += `| Slide Section | Text on Slide | Visual Prompt |\n`;
    markdown += `|--------------|---------------|---------------|\n`;
    visualAssets.forEach(asset => {
      markdown += `| ${asset.slideSection} | ${asset.textOnSlide} | ${asset.visualPrompt} |\n`;
    });
  }

  return markdown;
}
