import { Lecture, VisualAsset, WorshipSong } from '@/types/workflow';

export function exportToMarkdown(
  lecture: Lecture,
  visualAssets: VisualAsset[] = [],
  worshipSongs: WorshipSong[] = []
): string {
  let markdown = `# ${lecture.title}\n\n`;
  markdown += `**Scripture Reference:** ${lecture.scriptureReference}\n\n`;
  markdown += `*Generated by BSF Lecture Assistant*\n\n`;
  markdown += `---\n\n`;

  // Worship Songs Section
  if (worshipSongs.length > 0) {
    markdown += `## Worship Songs\n\n`;
    worshipSongs.forEach(song => {
      markdown += `### ${song.title}\n`;
      markdown += `- **Artist/Source:** ${song.artist} - ${song.source}\n`;
      markdown += `- **Category:** ${song.category}\n`;
      markdown += `- **Placement:** ${song.placement}\n`;
      markdown += `- **Thematic Connection:** ${song.thematicConnection}\n\n`;
    });
    markdown += `---\n\n`;
  }

  // Introduction
  markdown += `## Introduction\n\n`;
  markdown += `${lecture.introduction.storyOpening}\n\n`;
  markdown += `*(Story continues...)*\n\n`;

  // Body
  markdown += `---\n\n`;
  lecture.body.forEach((division, index) => {
    markdown += `## Division ${index + 1}: ${division.title}\n\n`;
    markdown += `**Scripture:** ${division.scriptureRange}\n\n`;
    markdown += `### Exposition\n${division.exposition}\n\n`;
    markdown += `### Principle\n${division.principle}\n\n`;
    markdown += `### Applications\n\n`;
    markdown += `**Young Professionals:** ${division.applications.youngProfessionals.question}\n\n`;
    markdown += `**Fathers/Mid-life:** ${division.applications.fathersMidLife.question}\n\n`;
    markdown += `**Elders:** ${division.applications.elders.question}\n\n`;
    markdown += `---\n\n`;
  });

  // Conclusion
  markdown += `## Conclusion\n\n`;
  markdown += `${lecture.conclusion.storyResolution}\n\n`;
  markdown += `### Call to Action\n${lecture.conclusion.callToAction}\n\n`;
  markdown += `### Closing Prayer\n${lecture.conclusion.closingPrayer}\n\n`;
  markdown += `---\n\n`;

  // Visual Assets
  if (visualAssets.length > 0) {
    markdown += `## Visual Assets (AI Image Prompts)\n\n`;
    markdown += `| Slide Section | Text on Slide | Visual Prompt |\n`;
    markdown += `|--------------|---------------|---------------|\n`;
    visualAssets.forEach(asset => {
      markdown += `| ${asset.slideSection} | ${asset.textOnSlide} | ${asset.visualPrompt} |\n`;
    });
  }

  return markdown;
}
